### ISSUE TITLE
bug: cmake parse_documentation.py fails

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1435]
We get a KeyError:

```python
-- Preparing documentation
Traceback (most recent call last):
  File "/home/dreamer/Sources/_audio/_plugins/plugdata/Resources/Scripts/parse_documentation.py", line 304, in <module>
    parseFilesInDir("../Documentation", False, False)
  File "/home/dreamer/Sources/_audio/_plugins/plugdata/Resources/Scripts/parse_documentation.py", line 285, in parseFilesInDir
    markdownToXml(root, f.read())
  File "/home/dreamer/Sources/_audio/_plugins/plugdata/Resources/Scripts/parse_documentation.py", line 233, in markdownToXml
    ET.SubElement(flags, "flag", name=sectionMap["name"], description=desc)
                                      ~~~~~~~~~~^^^^^^^^
KeyError: 'name'
```

**Comment by timothyschoen** [comment]
Fixed!
