### ISSUE TITLE
Bug: segfault when resizing Heavy help dialog

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1443]
When pulling on the window corner handles:

```gdb
[Thread 0x7fffbd11b6c0 (LWP 598356) exited]
JUCE Assertion failure in juce_Image.cpp:410

Thread 1 "plugdata" received signal SIGSEGV, Segmentation fault.
0x000055555623c690 in juce::RenderingHelpers::ClipRegions<juce::RenderingHelpers::SoftwareRendererSavedState>::RectangleListRegion::fillRectWithColour(juce::RenderingHelpers::SoftwareRendererSavedState&, juce::Rectangle<int>, juce::PixelARGB, bool) const ()
(gdb) bt
#0  0x000055555623c690 in juce::RenderingHelpers::ClipRegions<juce::RenderingHelpers::SoftwareRendererSavedState>::RectangleListRegion::fillRectWithColour(juce::RenderingHelpers::SoftwareRendererSavedState&, juce::Rectangle<int>, juce::PixelARGB, bool) const ()
#1  0x00005555561cf188 in juce::Image::clear(juce::Rectangle<int> const&, juce::Colour) ()
#2  0x00005555561797c9 in juce::LinuxComponentPeer::LinuxRepaintManager::performAnyPendingRepaintsNow() ()
#3  0x0000555556294879 in juce::Timer::TimerThread::callTimers() ()
#4  0x0000555556295981 in juce::Timer::TimerThread::CallTimersMessage::messageCallback() ()
#5  0x0000555556294207 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#6  0x00005555562858c0 in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#7  0x000055555628ffd1 in juce::MessageManager::runDispatchLoop() ()
#8  0x000055555593c0e9 in juce::JUCEApplicationBase::main() ()
#9  0x00007ffff746e24a in __libc_start_call_main (main=main@entry=0x55555585e120 <main>, 
    argc=argc@entry=1, argv=argv@entry=0x7fffffffdec8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#10 0x00007ffff746e305 in __libc_start_main_impl (main=0x55555585e120 <main>, argc=1, 
--Type <RET> for more, q to quit, c to continue without paging--
    argv=0x7fffffffdec8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdeb8) at ../csu/libc-start.c:360
#11 0x0000555555944ba1 in _start ()
```

When using Alt+RMB X11 resize feature it works correctly.

**Comment by timothyschoen** [comment]
<img width="440" alt="Screenshot 2024-02-19 at 15 06 35" src="https://github.com/plugdata-team/plugdata/assets/44585538/49fda2d0-581f-455c-ac49-487a43a7ed83">

It even crashes X11 over here! Whoops!

**Comment by timothyschoen** [comment]
This is fixed! Also for suggestionscomponent. 

I just disabled the host managed resizing for now, because I couldn't get it to work that way.

**Comment by dromer** [comment]
Yup it no longer crashes!

Only weird thing is that now I can barely move it around when dragging the top handle.
Using Alt+LMB X11 move it can move anywhere.
