### ISSUE TITLE
Bug: compiling just segfaults

### ISSUE THREAD

**Issue by dromer** [plugdata-team/plugdata#1960]
On latest develop.

Must have been introduced in the past couple days since not too long ago it still worked fine.

Basic gdb trace of non-debug build:

```gdb
Thread 1 "plugdata" received signal SIGSEGV, Segmentation fault.
0x00005555561e019e in juce::String::operator=(juce::String const&) ()
(gdb) bt
#0  0x00005555561e019e in juce::String::operator=(juce::String const&) ()
#1  0x00005555561e0219 in juce::File::operator=(juce::File const&) ()
#2  0x00005555559f6d2e in non-virtual thunk to ExporterSettingsPanel::selectedRowsChanged(int) ()
#3  0x0000555556003aab in juce::ListBox::deselectAllRows() ()
#4  0x0000555555a0f9dc in ExporterSettingsPanel::ExporterSettingsPanel(PluginEditor*, ExportingProgressView*) ()
#5  0x00005555559f5eb9 in HeavyExportDialog::HeavyExportDialog(Dialog*) ()
#6  0x000055555597b610 in Dialogs::showHeavyExportDialog(std::unique_ptr<Dialog, std::default_delete<Dialog> >*, juce::Component*) ()
#7  0x0000555555988203 in std::_Function_handler<void (int), Dialogs::showMainMenu(PluginEditor*, juce::Component*)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#8  0x000055555582a07a in std::_Function_handler<void (int), ArrowPopupMenu::showMenuAsync(juce::PopupMenu*, juce::PopupMenu::Options const&, std::function<void (int)> const&, ArrowPopupMenu::ArrowDirection)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#9  0x000055555605d8ae in juce::ModalCallbackFunction::create<std::function<void (int)>&>(std::function<void (int)>&)::Callable::modalStateFinished(int) ()
#10 0x0000555555f9fba6 in juce::ModalComponentManager::handleAsyncUpdate() ()
#11 0x00005555561d27f7 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#12 0x00005555561c3ab0 in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#13 0x00005555561ce471 in juce::MessageManager::runDispatchLoop() ()
#14 0x00005555557f5199 in juce::JUCEApplicationBase::main() ()
#15 0x00007ffff754d24a in __libc_start_call_main (main=main@entry=0x555555725950 <main>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdb38) at ../sysdeps/nptl/libc_start_call_main.h:58
#16 0x00007ffff754d305 in __libc_start_main_impl (main=0x555555725950 <main>, argc=1, argv=0x7fffffffdb38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdb28) at ../csu/libc-start.c:360
#17 0x00005555557f7c91 in _start ()
```

**Comment by dromer** [comment]
Can no longer be reproduced.
