### ISSUE TITLE
opening settings causes crash

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#397]
Opening settings can crash e5bb760
```
OS: EndeavourOS Linux x86_64 
Host: MS-7B98 1.0 
Kernel: 6.1.6-arch1-3 
Uptime: 24 mins 
Packages: 2360 (pacman), 10 (flatpak), 3 (snap) 
Shell: bash 5.1.16 
Resolution: 1920x1080, 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: tilix 
CPU: Intel i5-8600K (6) @ 4.400GHz 
GPU: NVIDIA GeForce RTX 3090 
Memory: 2751MiB / 15934MiB 
```

<details><summary>backtrace</summary>
<p>

```
Thread 1 "plugdata" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	      return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff76a16b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7651938 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff763b53d in __GI_abort () at abort.c:79
#4  0x00007ffff789a833 in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x00007ffff78a6ccc in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x00007ffff78a6d39 in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x00007ffff78a6f9d in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7ffff7a2a148 <typeinfo for std::out_of_range>, dest=0x7ffff78be6e0 <std::out_of_range::~out_of_range()>)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#8  0x00007ffff789d52b in std::__throw_out_of_range (__s=0x555556b46732 "map::at") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/functexcept.cc:86
#9  0x0000555556099440 in std::map<juce::String, std::map<PlugDataColour, juce::Colour, std::less<PlugDataColour>, std::allocator<std::pair<PlugDataColour const, juce::Colour> > >, std::less<juce::String--Type <RET> for more, q to quit, c to continue without paging--
>, std::allocator<std::pair<juce::String const, std::map<PlugDataColour, juce::Colour, std::less<PlugDataColour>, std::allocator<std::pair<PlugDataColour const, juce::Colour> > > > > >::at(juce::String const&) ()
#10 0x0000555556069d46 in PlugDataLook::setTheme(juce::String) ()
#11 0x0000555556077a27 in ThemePanel::ThemePanel(juce::ValueTree)::{lambda()#6}::operator()() ()
#12 0x00005555560ce5ca in void std::__invoke_impl<void, ThemePanel::ThemePanel(juce::ValueTree)::{lambda()#6}&>(std::__invoke_other, ThemePanel::ThemePanel(juce::ValueTree)::{lambda()#6}&) ()
#13 0x00005555560c3490 in std::enable_if<is_invocable_r_v<void, ThemePanel::ThemePanel(juce::ValueTree)::{lambda()#6}&>, void>::type std::__invoke_r<void, ThemePanel::ThemePanel(juce::ValueTree)::{lambda()#6}&>(ThemePanel::ThemePanel(juce::ValueTree)::{lambda()#6}&) ()
#14 0x00005555560b5a72 in std::_Function_handler<void (), ThemePanel::ThemePanel(juce::ValueTree)::{lambda()#6}>::_M_invoke(std::_Any_data const&) ()
#15 0x0000555556019654 in std::function<void ()>::operator()() const ()
#16 0x00005555563b4ee8 in juce::ComboBox::handleAsyncUpdate() ()
#17 0x000055555663961f in juce::AsyncUpdater::AsyncUpdaterMessage::messageCallback() ()
#18 0x000055555663bacf in juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}::operator()(int) const ()
#19 0x000055555664b814 in void std::__invoke_impl<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(std::__invoke_other, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) ()
#20 0x0000555556648103 in std::enable_if<is_invocable_r_v<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>, void>::type std::__invoke_r<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) ()
#21 0x0000555556643e76 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#22 0x0000555556099792 in std::function<void (int)>::operator()(int) const ()
#23 0x0000555556636c79 in juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}::operator()() const ()
#24 0x0000555556637c4e in void std::__invoke_impl<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(std::__invoke_other, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
--Type <RET> for more, q to quit, c to continue without paging--
#25 0x00005555566376a6 in std::enable_if<is_invocable_r_v<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>, void>::type std::__invoke_r<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
#26 0x0000555556637360 in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#27 0x0000555556019654 in std::function<void ()>::operator()() const ()
#28 0x000055555663c382 in juce::InternalRunLoop::dispatchPendingEvents() ()
#29 0x0000555556636c2c in juce::dispatchNextMessageOnSystemQueue(bool) ()
#30 0x00005555566311d5 in juce::MessageManager::runDispatchLoop() ()
#31 0x00005555566307db in juce::JUCEApplicationBase::main() ()
#32 0x000055555663070a in juce::JUCEApplicationBase::main(int, char const**) ()
#33 0x0000555556243615 in main ()
```

</p>
</details>

**Comment by timothyschoen** [comment]
The problem is probably that "Theme" is still set to "1" in settings.xml. It should now be set to "dark" or "light". It should've automatically fixed that...

**Comment by timothyschoen** [comment]
I can't reproduce this anymore on the latest version, is it also fixed for you?
