### ISSUE TITLE
[onebang_proxy] causes crash

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#570]
put one, then another one. that causes a crash
another way is to put one, then delete it
sometimes just putting one of them is enough

edit: still there after updating cyclone

backtraces:
old:
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff76a277f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff76561a2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7640477 in __GI_abort () at abort.c:79
#4  0x00007ffff7696987 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff77b36cf "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff76ac40c in malloc_printerr (str=str@entry=0x7ffff77b6398 "free(): invalid next size (fast)") at malloc.c:5660
#6  0x00007ffff76adfc5 in _int_free (av=0x7ffff77f1aa0 <main_arena>, p=0x55555ce041a0, have_lock=0) at malloc.c:4518
#7  0x00007ffff76b0b2f in __GI___libc_free (mem=<optimized out>) at malloc.c:3385
#8  0x00005555569844ce in freebytes ()
#9  0x00005555569870cd in pd_free ()
#10 0x000055555695a612 in glist_delete ()
#11 0x00005555569b696e in libpd_canvas_doclear ()
#12 0x00005555569b6a3b in libpd_removeselection ()
#13 0x000055555624b375 in pd::Patch::removeSelection()::{lambda()#1}::operator()() ()
#14 0x00005555562516de in void std::__invoke_impl<void, pd::Patch::removeSelection()::{lambda()#1}&>(std::__invoke_other, pd::Patch::removeSelection()::{lambda()#1}&) ()
#15 0x00005555562501c4 in std::enable_if<is_invocable_r_v<void, pd::Patch::removeSelection()::{lambda()#1}&>, void>::type std::__invoke_r<void, pd::Patch::removeSelection()::{lambda()#1}&>(pd::Patch::removeSelection()::{lambda()#1}&) ()
#16 0x000055555624dfdf in std::_Function_handler<void (), pd::Patch::removeSelection()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#17 0x0000555556080172 in std::function<void ()>::operator()() const ()
#18 0x0000555556216256 in pd::Instance::sendMessagesFromQueue() ()
#19 0x0000555556275534 in PluginProcessor::messageEnqueued() ()
#20 0x00005555562156f3 in pd::Instance::enqueueFunction(std::function<void ()> const&) ()
#21 0x000055555624b3c5 in pd::Patch::removeSelection() ()
#22 0x0000555556061645 in Canvas::removeSelection() ()
#23 0x00005555562607ff in PluginEditor::perform(juce::ApplicationCommandTarget::InvocationInfo const&) ()
#24 0x000055555648720e in juce::ApplicationCommandTarget::tryToInvoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) ()
#25 0x00005555564875a4 in juce::ApplicationCommandTarget::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) ()
#26 0x0000555556486c35 in juce::ApplicationCommandManager::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) ()
#27 0x000055555648827b in juce::KeyPressMappingSet::invokeCommand(int, juce::KeyPress const&, bool, int, juce::Component*) const ()
#28 0x0000555556488cf6 in juce::KeyPressMappingSet::keyPressed(juce::KeyPress const&, juce::Component*) ()
#29 0x000055555647dbe3 in juce::ComponentPeer::handleKeyPress(juce::KeyPress const&) ()
#30 0x000055555647db1d in juce::ComponentPeer::handleKeyPress(int, wchar_t) ()
#31 0x000055555649d038 in juce::XWindowSystem::handleKeyPressEvent(juce::LinuxComponentPeer*, XKeyEvent&) const ()
#32 0x000055555649c890 in juce::XWindowSystem::handleWindowMessage(juce::LinuxComponentPeer*, _XEvent&) const ()
#33 0x000055555649eb0b in juce::XWindowSystem::windowMessageReceive(_XEvent&) ()
#34 0x000055555649c0be in juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}::operator()(int) const ()
#35 0x00005555564b4d80 in void std::__invoke_impl<void, juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int>(std::__invoke_other, juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int&&) ()
#36 0x00005555564afe18 in std::enable_if<is_invocable_r_v<void, juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int>, void>::type std::__invoke_r<void, juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int>(juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int&&) ()
#37 0x00005555564aaec1 in std::_Function_handler<void (int), juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#38 0x000055555611338a in std::function<void (int)>::operator()(int) const ()
#39 0x00005555566dc891 in juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}::operator()() const ()
#40 0x00005555566dd866 in void std::__invoke_impl<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(std::__invoke_other, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
#41 0x00005555566dd2be in std::enable_if<is_invocable_r_v<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>, void>::type std::__invoke_r<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
#42 0x00005555566dcf78 in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#43 0x0000555556080172 in std::function<void ()>::operator()() const ()
#44 0x00005555566e1f9a in juce::InternalRunLoop::dispatchPendingEvents() ()
#45 0x00005555566dc844 in juce::dispatchNextMessageOnSystemQueue(bool) ()
#46 0x00005555566d6ded in juce::MessageManager::runDispatchLoop() ()
#47 0x00005555566d63f3 in juce::JUCEApplicationBase::main() ()
#48 0x00005555566d6322 in juce::JUCEApplicationBase::main(int, char const**) ()
#49 0x00005555562ea873 in main ()
```

new:
```
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff76a277f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff76561a2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7640477 in __GI_abort () at abort.c:79
#4  0x00007ffff7696987 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff77b36cf "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff76ac40c in malloc_printerr (str=str@entry=0x7ffff77b6780 "malloc(): unaligned fastbin chunk detected") at malloc.c:5660
#6  0x00007ffff76af031 in _int_malloc (av=av@entry=0x7ffff77f1aa0 <main_arena>, bytes=bytes@entry=120) at malloc.c:3849
#7  0x00007ffff76b1382 in __libc_calloc (n=<optimized out>, elem_size=<optimized out>) at malloc.c:3674
#8  0x000055555698e285 in getbytes ()
#9  0x000055555696cf39 in rtext_new ()
#10 0x0000555556963fdd in glist_add ()
#11 0x000055555697b9ac in canvas_objtext ()
#12 0x000055555697bdb2 in canvas_obj ()
#13 0x000055555698ca26 in pd_typedmess ()
#14 0x00005555569c18ba in libpd_createobj ()
#15 0x000055555624c56c in pd::Patch::createObject(juce::String const&, int, int)::{lambda()#1}::operator()() ()
#16 0x000055555625622a in void std::__invoke_impl<void, pd::Patch::createObject(juce::String const&, int, int)::{lambda()#1}&>(std::__invoke_other, pd::Patch::createObject(juce::String const&, int, int)::{lambda()#1}&) ()
#17 0x0000555556254016 in std::enable_if<is_invocable_r_v<void, pd::Patch::createObject(juce::String const&, int, int)::{lambda()#1}&>, void>::type std::__invoke_r<void, pd::Patch::createObject(juce::String const&, int, int)::{lambda()#1}&>(pd::Patch::createObject(juce::String const&, int, int)::{lambda()#1}&) ()
#18 0x000055555625271b in std::_Function_handler<void (), pd::Patch::createObject(juce::String const&, int, int)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#19 0x00005555560850c8 in std::function<void ()>::operator()() const ()
#20 0x000055555621b7e2 in pd::Instance::sendMessagesFromQueue() ()
#21 0x000055555627b6f6 in PluginProcessor::messageEnqueued() ()
#22 0x000055555621ac81 in pd::Instance::enqueueFunction(std::function<void ()> const&) ()
#23 0x000055555624da63 in pd::Patch::createObject(juce::String const&, int, int) ()
#24 0x00005555561861ee in Object::setType(juce::String const&, void*) ()
#25 0x000055555618a89d in Object::hideEditor() ()
#26 0x000055555618ac46 in Object::openNewObjectEditor()::{lambda()#2}::operator()() const ()
#27 0x000055555618ec60 in void std::__invoke_impl<void, Object::openNewObjectEditor()::{lambda()#2}&>(std::__invoke_other, Object::openNewObjectEditor()::{lambda()#2}&)
    ()
#28 0x000055555618e102 in std::enable_if<is_invocable_r_v<void, Object::openNewObjectEditor()::{lambda()#2}&>, void>::type std::__invoke_r<void, Object::openNewObjectEditor()::{lambda()#2}&>(Object::openNewObjectEditor()::{lambda()#2}&) ()
#29 0x000055555618d468 in std::_Function_handler<void (), Object::openNewObjectEditor()::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
#30 0x00005555560850c8 in std::function<void ()>::operator()() const ()
#31 0x000055555653521e in void juce::NullCheckedInvocation::invoke<std::function<void ()>&>(std::function<void ()>&) ()
#32 0x00005555564785f3 in juce::TextEditor::handleCommandMessage(int) ()
#33 0x00005555563f8303 in juce::Component::postCommandMessage(int)::{lambda()#1}::operator()() const ()
--Type <RET> for more, q to quit, c to continue without paging--
#34 0x00005555564b9f4a in void std::__invoke_impl<void, juce::Component::postCommandMessage(int)::{lambda()#1}&>(std::__invoke_other, juce::Component::postCommandMessage(int)::{lambda()#1}&) ()
#35 0x00005555564b527e in std::enable_if<is_invocable_r_v<void, juce::Component::postCommandMessage(int)::{lambda()#1}&>, void>::type std::__invoke_r<void, juce::Component::postCommandMessage(int)::{lambda()#1}&>(juce::Component::postCommandMessage(int)::{lambda()#1}&) ()
#36 0x00005555564b0e8b in std::_Function_handler<void (), juce::Component::postCommandMessage(int)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#37 0x00005555560850c8 in std::function<void ()>::operator()() const ()
#38 0x00005555566e0ff2 in juce::MessageManager::callAsync(std::function<void ()>)::AsyncCallInvoker::messageCallback() ()
#39 0x00005555566eb5f1 in juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}::operator()(int) const ()
#40 0x00005555566fb336 in void std::__invoke_impl<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(std::__invoke_other, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) ()
#41 0x00005555566f7c25 in std::enable_if<is_invocable_r_v<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>, void>::type std::__invoke_r<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) ()
#42 0x00005555566f3998 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#43 0x00005555561183e8 in std::function<void (int)>::operator()(int) const ()
#44 0x00005555566e679b in juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}::operator()() const ()
#45 0x00005555566e7770 in void std::__invoke_impl<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(std::__invoke_other, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
#46 0x00005555566e71c8 in std::enable_if<is_invocable_r_v<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>, void>::type std::__invoke_r<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
#47 0x00005555566e6e82 in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#48 0x00005555560850c8 in std::function<void ()>::operator()() const ()
#49 0x00005555566ebea4 in juce::InternalRunLoop::dispatchPendingEvents() ()
#50 0x00005555566e674e in juce::dispatchNextMessageOnSystemQueue(bool) ()
#51 0x00005555566e0cf7 in juce::MessageManager::runDispatchLoop() ()
#52 0x00005555566e02fd in juce::JUCEApplicationBase::main() ()
#53 0x00005555566e022c in juce::JUCEApplicationBase::main(int, char const**) ()
#54 0x00005555562f479b in main ()
```

**Comment by tomara-x** [comment]
yes!
