### ISSUE TITLE
crash when object has a connection and a send symbol

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#583]
this is just two numboxes connected, pasting it works fine
```
#X obj 340 180 nbx 4 18 -1e+37 1e+37 0 0 empty empty empty 0 -8 0 10 #191919 #ffffff #ffffff 0 256;
#X obj 300 240 nbx 4 18 -1e+37 1e+37 0 0 empty empty empty 0 -8 0 10 #191919 #ffffff #ffffff 0 256;
#X connect 0 0 1 0 empty;
```
adding a send symbol to one, will make it crash. try pasting this into a patch:
```
#X obj 340 180 nbx 4 18 -1e+37 1e+37 0 0 hello empty empty 0 -8 0 10 #191919 #ffffff #ffffff 0 256;
#X obj 300 240 nbx 4 18 -1e+37 1e+37 0 0 empty empty empty 0 -8 0 10 #191919 #ffffff #ffffff 0 256;
#X connect 0 0 1 0 empty;
```
if you add a receive symbol it will work fine. the connection and iolets are hidden but it still functions as if the connection is there
```
#X obj 340 180 nbx 4 18 -1e+37 1e+37 0 0 hello hi empty 0 -8 0 10 #191919 #ffffff #ffffff 0 256;
#X obj 300 240 nbx 4 18 -1e+37 1e+37 0 0 empty empty empty 0 -8 0 10 #191919 #ffffff #ffffff 0 256;
#X connect 0 0 1 0 empty;
```

backtrace:
```
0x00005555560a8c6c in Connection::Connection(Canvas*, Iolet*, Iolet*, void*) ()
(gdb) bt
#0  0x00005555560a8c6c in Connection::Connection(Canvas*, Iolet*, Iolet*, void*) ()
#1  0x000055555605e505 in Canvas::synchronise(bool) ()
#2  0x0000555556060484 in Canvas::pasteSelection() ()
#3  0x00005555562607a0 in PluginEditor::perform(juce::ApplicationCommandTarget::InvocationInfo const&) ()
#4  0x000055555648720e in juce::ApplicationCommandTarget::tryToInvoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) ()
#5  0x00005555564875a4 in juce::ApplicationCommandTarget::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) ()
#6  0x0000555556486c35 in juce::ApplicationCommandManager::invoke(juce::ApplicationCommandTarget::InvocationInfo const&, bool) ()
#7  0x000055555648827b in juce::KeyPressMappingSet::invokeCommand(int, juce::KeyPress const&, bool, int, juce::Component*) const ()
#8  0x0000555556488cf6 in juce::KeyPressMappingSet::keyPressed(juce::KeyPress const&, juce::Component*) ()
#9  0x000055555647dbe3 in juce::ComponentPeer::handleKeyPress(juce::KeyPress const&) ()
#10 0x000055555647db1d in juce::ComponentPeer::handleKeyPress(int, wchar_t) ()
#11 0x000055555649d038 in juce::XWindowSystem::handleKeyPressEvent(juce::LinuxComponentPeer*, XKeyEvent&) const ()
#12 0x000055555649c890 in juce::XWindowSystem::handleWindowMessage(juce::LinuxComponentPeer*, _XEvent&) const ()
#13 0x000055555649eb0b in juce::XWindowSystem::windowMessageReceive(_XEvent&) ()
#14 0x000055555649c0be in juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}::operator()(int) const ()
#15 0x00005555564b4d80 in void std::__invoke_impl<void, juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int>(std::__invoke_other, juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int&&) ()
#16 0x00005555564afe18 in std::enable_if<is_invocable_r_v<void, juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int>, void>::type std::__invoke_r<void, juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int>(juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}&, int&&) ()
#17 0x00005555564aaec1 in std::_Function_handler<void (int), juce::XWindowSystem::initialiseXDisplay()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#18 0x000055555611338a in std::function<void (int)>::operator()(int) const ()
#19 0x00005555566dc891 in juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}::operator()() const ()
#20 0x00005555566dd866 in void std::__invoke_impl<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(std::__invoke_other, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
#21 0x00005555566dd2be in std::enable_if<is_invocable_r_v<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>, void>::type std::__invoke_r<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
#22 0x00005555566dcf78 in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#23 0x0000555556080172 in std::function<void ()>::operator()() const ()
#24 0x00005555566e1f9a in juce::InternalRunLoop::dispatchPendingEvents() ()
#25 0x00005555566dc844 in juce::dispatchNextMessageOnSystemQueue(bool) ()
#26 0x00005555566d6ded in juce::MessageManager::runDispatchLoop() ()
#27 0x00005555566d63f3 in juce::JUCEApplicationBase::main() ()
#28 0x00005555566d6322 in juce::JUCEApplicationBase::main(int, char const**) ()
#29 0x00005555562ea873 in main ()
```

**Comment by timothyschoen** [comment]
Fixed it, turns out that in Pd-vanilla, the iolets are just hidden instead of not there at all, I misunderstood that.
