### ISSUE TITLE
Segfault when closing with properties panel open

### ISSUE THREAD

**Issue by haenkel** [plugdata-team/plugdata#597]
Linux, built at 8ef4c200

- new patch
- add slider
- click slider to open properties
- close patch tab
- choose "Don't Save"
- crash

```gdb
Thread 1 "plugdata" received signal SIGSEGV, Segmentation fault.
juce::Value::toString (this=0x55555d1230f8) at xxx/plugdata/Libraries/JUCE/modules/juce_data_structures/values/juce_Value.cpp:168
168	    return value->getValue().toString();
(gdb) where
#0  juce::Value::toString (this=0x55555d1230f8)
    at xxx/plugdata/Libraries/JUCE/modules/juce_data_structures/values/juce_Value.cpp:168
#1  0x00005555561e3d54 in PropertiesPanel::ColourComponent::paint (
    this=0x55555d089870, g=...)
    at xxx/plugdata/Source/Dialogs/../Utility/PropertiesPanel.h:275
#2  0x000055555653cd72 in juce::Component::paintComponentAndChildren (
    this=0x55555d089870, g=...)
    at xxx/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:2010
#3  0x000055555653d4b9 in juce::Component::paintEntireComponent (
    this=0x55555d089870, g=..., ignoreAlphaLevel=false)
    at xxx/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:2107
#4  0x000055555653cc46 in juce::Component::paintWithinParentContext (
    this=0x55555d089870, g=...)
    at xxx/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:1994
#5  0x000055555653d015 in juce::Component::paintComponentAndChildren (
    this=0x55555d0a3420, g=...)
    at xxx/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:2052
#6  0x000055555653d4b9 in juce::Component::paintEntireComponent (
    this=0x55555d0a3420, g=..., ignoreAlphaLevel=false)
    at xxx/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:2107
#7  0x000055555653cc46 in juce::Component::paintWithinParentContext (
    this=0x55555d0a3420, g=...)
    at xxx/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:1994
#8  0x000055555653d015 in juce::Component::paintComponentAndChildren (
    this=0x55555c933240, g=...)
    at xxx/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:2052
#9  0x000055555653d4b9 in juce::Component::paintEntireComponent (
    this=0x55555c933240, g=..., ignoreAlphaLevel=false)
    at xxx/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:2107
```

**Comment by timothyschoen** [comment]
Thanks, fixed it with 0d150cd9b25f21eb7eeb0a4d0dbfbf156b69c0eb!
