### ISSUE TITLE
crash when giving plaits negative frequency

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#601]
edit: it has to be connected to output/dac

```
Thread 6 "JUCE ALSA" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeebfe6c0 (LWP 4820)]
0x0000555556bab9e6 in stmlib::SemitonesToRatio(float) ()
(gdb) bt
#0  0x0000555556bab9e6 in stmlib::SemitonesToRatio(float) ()
#1  0x0000555556baba7c in plaits::NoteToFrequency(float) ()
#2  0x0000555556bbd86e in plaits::VirtualAnalogEngine::Render(plaits::EngineParameters const&, float*, float*, unsigned long, bool*) ()
#3  0x0000555556bab4bb in plaits::Voice::Render(plaits::Patch const&, plaits::Modulations const&, plaits::Voice::Frame*, unsigned long) ()
#4  0x0000555556b21d46 in plts_perform ()
#5  0x00005555569edb01 in dsp_tick ()
#6  0x00005555569a353c in sched_tick ()
#7  0x00005555569bb7f9 in libpd_process_raw ()
#8  0x000055555622a29d in pd::Instance::performDSP(float const*, float*) ()
#9  0x000055555628c952 in PluginProcessor::processInternal() ()
#10 0x000055555628ad6a in PluginProcessor::process(juce::dsp::AudioBlock<float>, juce::MidiBuffer&) ()
#11 0x000055555628a277 in PluginProcessor::processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) ()
#12 0x00005555563246a7 in juce::AudioProcessorPlayer::audioDeviceIOCallbackWithContext(float const* const*, int, float* const*, int, int, juce::AudioIODeviceCallbackContext const&) ()
#13 0x000055555630d911 in StandalonePluginHolder::audioDeviceIOCallbackWithContext(float const* const*, int, float* const*, int, int, juce::AudioIODeviceCallbackContext const&) ()
#14 0x000055555630d82d in StandalonePluginHolder::CallbackMaxSizeEnforcer::audioDeviceIOCallbackWithContext(float const* const*, int, float* const*, int, int, juce::AudioIODeviceCallbackContext const&) ()
#15 0x00005555568d17ba in juce::AudioDeviceManager::audioDeviceIOCallbackInt(float const* const*, int, float* const*, int, int, juce::AudioIODeviceCallbackContext const&) ()
#16 0x00005555568dd336 in juce::AudioDeviceManager::CallbackHandler::audioDeviceIOCallbackWithContext(float const* const*, int, float* const*, int, int, juce::AudioIODeviceCallbackContext const&) ()
#17 0x00005555568c7e94 in juce::(anonymous namespace)::ALSAThread::run() ()
#18 0x000055555673bf5c in juce::Thread::threadEntryPoint() ()
#19 0x000055555673c032 in juce::juce_threadEntryPoint(void*) ()
#20 0x0000555556764d4a in juce::Thread::createNativeThread(juce::Thread::Priority)::{lambda(void*)#1}::operator()(void*) const ()
#21 0x0000555556764d6e in juce::Thread::createNativeThread(juce::Thread::Priority)::{lambda(void*)#1}::_FUN(void*) ()
#22 0x00007ffff76a0afa in start_thread (arg=<optimized out>)
    at pthread_create.c:442
#23 0x00007ffff772173c in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by tomara-x** [comment]
crash no more :3
