### ISSUE TITLE
[crash][bt] reconnecting signal cable

### ISSUE THREAD

**Issue by alcomposer** [plugdata-team/plugdata#602]
### Steps to reproduce:
* Connect signal cables between objects
* Reconnect any of the signal cables
* They may not reconnect
* Try to make a new connection between the signal iolets
* crash

[screencast](https://user-images.githubusercontent.com/12004932/221472104-81232cec-8fef-4f98-880e-77ff1629c6f6.mp4)

<details><summary>backtrace:</summary>
<p>

```
Thread 1 "plugdata" received signal SIGSEGV, Segmentation fault.
juce::CharPointer_UTF8::isEmpty (this=0x7fffffffd8b8) at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_core/text/juce_CharPointer_UTF8.h:73
73	    bool isEmpty() const noexcept                { return *data == 0; }
(gdb) bt
#0  juce::CharPointer_UTF8::isEmpty (this=0x7fffffffd8b8) at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_core/text/juce_CharPointer_UTF8.h:73
#1  0x00005555568e8aa2 in juce::StringHolderUtils::createFromCharPointer<juce::CharPointer_UTF8> (text=...)
    at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_core/text/juce_String.cpp:80
#2  0x000055555687d52d in juce::String::String (this=0x7fffffffd998, t=...) at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_core/text/juce_String.cpp:342
#3  0x000055555688346f in juce::String::fromUTF8 (buffer=0x555009115600 <error: Cannot access memory at address 0x555009115600>, bufferSizeBytes=-1)
    at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_core/text/juce_String.cpp:2130
#4  0x00005555561c3656 in Connection::popPathState (this=0x55555b8beca0) at /home/alexmitchell/Documents/github/plugdata/Source/Connection.cpp:140
#5  0x000055555617550e in Canvas::synchronise (this=0x55555c41cbf0, updatePosition=true) at /home/alexmitchell/Documents/github/plugdata/Source/Canvas.cpp:307
#6  0x000055555629a222 in Iolet::createConnection (this=0x55555c3b9330) at /home/alexmitchell/Documents/github/plugdata/Source/Iolet.cpp:372
#7  0x0000555556298ea3 in operator() (__closure=0x55555c450140) at /home/alexmitchell/Documents/github/plugdata/Source/Iolet.cpp:186
#8  0x000055555629b862 in std::__invoke_impl<void, Iolet::mouseUp(const juce::MouseEvent&)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/12.2.1/bits/invoke.h:61
--Type <RET> for more, q to quit, c to continue without paging--
#9  0x000055555629b4c8 in std::__invoke_r<void, Iolet::mouseUp(const juce::MouseEvent&)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/12.2.1/bits/invoke.h:111
#10 0x000055555629b0dd in std::_Function_handler<void(), Iolet::mouseUp(const juce::MouseEvent&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/12.2.1/bits/std_function.h:290
#11 0x0000555556197508 in std::function<void ()>::operator()() const (this=0x55555baed0a0) at /usr/include/c++/12.2.1/bits/std_function.h:591
#12 0x0000555556839f7e in AsyncCallInvoker::messageCallback (this=0x55555baed090) at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_events/messages/juce_MessageManager.cpp:197
#13 0x0000555556844bbf in juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}::operator()(int) const (__closure=0x55555b7d46b0, fd=4)
    at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:42
#14 0x0000555556857970 in std::__invoke_impl<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(std::__invoke_other, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) (__f=...) at /usr/include/c++/12.2.1/bits/invoke.h:61
#15 0x0000555556854127 in std::__invoke_r<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) (
    __fn=...) at /usr/include/c++/12.2.1/bits/invoke.h:111
#16 0x000055555684eb58 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) (__functor=..., 
    __args#0=@0x7fffffffdfb4: 4) at /usr/include/c++/12.2.1/bits/std_function.h:290
#17 0x000055555622ec86 in std::function<void (int)>::operator()(int) const (this=0x55555b7d46b0, __args#0=4) at /usr/include/c++/12.2.1/bits/std_function.h:591
#18 0x000055555683fab9 in operator() (__closure=0x55555b7d46b0) at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:357
#19 0x0000555556840a8e in std::__invoke_impl<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/c++/12.2.1/bits/invoke.h:61
#20 0x00005555568404e6 in std::__invoke_r<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()>&>(struct {...} &) (__fn=...)
    at /usr/include/c++/12.2.1/bits/invoke.h:111
#21 0x00005555568401a0 in std::_Function_handler<void(), juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()> >::_M_invoke(const std::_Any_data &) (
    __functor=...) at /usr/include/c++/12.2.1/bits/std_function.h:290
#22 0x0000555556197508 in std::function<void ()>::operator()() const (this=0x55555b7d45d0) at /usr/include/c++/12.2.1/bits/std_function.h:591
#23 0x00005555568454ea in juce::InternalRunLoop::dispatchPendingEvents (this=0x55555b7d4600)
    at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:180
#24 0x000055555683fa6c in juce::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=false)
    at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:340
#25 0x0000555556839c3b in juce::MessageManager::runDispatchLoop (this=0x55555b7996e0)
    at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_events/messages/juce_MessageManager.cpp:109
#26 0x0000555556839155 in juce::JUCEApplicationBase::main () at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:265
#27 0x0000555556839054 in juce::JUCEApplicationBase::main (argc=1, argv=0x7fffffffe2a8)
    at /home/alexmitchell/Documents/github/plugdata/Libraries/JUCE/modules/juce_events/messages/juce_ApplicationBase.cpp:243
#28 0x0000555556418cf0 in main (argc=1, argv=0x7fffffffe2a8) at /home/alexmitchell/Documents/github/plugdata/Source/Standalone/PlugDataApp.cpp:273
```

</p>
</details>

**Comment by timothyschoen** [comment]
Should be fixed!
