### ISSUE TITLE
keyboard object can't be created from plus menu

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#678]
it works fine when typing "keyboard" into an empty object

another issue, the linux pasting text by middle clicking doesn't work, but that's fine, the problem is when i tried doing that, then i tried ctrl-v of the text "keyboard" it caused a crash (so middle click, then reselect the object, then ctrl-v, then enter)
it only happens with "keyboard", i tried with a bunch of other objects

https://user-images.githubusercontent.com/86204514/224657813-ab299e82-db49-4022-9fd9-062baf283d0e.mp4

backtraces from debug
```
Thread 1 "plugdata" received signal SIGSEGV, Segmentation fault.
0x0000555556065075 in gobj_getrect ()
(gdb) bt
#0  0x0000555556065075 in gobj_getrect ()
#1  0x00005555560dca51 in libpd_get_object_bounds ()
#2  0x0000555555f25719 in TextObjectHelper::recalculateTextObjectBounds(void*, void*, juce::String const&, int, int&, bool, int) ()
#3  0x0000555555f26bf4 in TextBase::getPdBounds() ()
#4  0x0000555555eee5ca in Object::updateBounds() ()
#5  0x0000555555f3920e in KeyboardObject::KeyboardObject(void*, Object*) ()
#6  0x0000555555f0ff98 in ObjectBase::createGui(void*, Object*) ()
#7  0x0000555555eeeb23 in Object::setType(juce::String const&, void*) ()
#8  0x0000555555f27097 in TextBase::hideEditor() ()
#9  0x0000555555f271eb in TextBase::showEditor()::{lambda()#1}::operator()() const ()
#10 0x0000555555f72e10 in void std::__invoke_impl<void, TextBase::showEditor()::{lambda()#1}&>(std::__invoke_other, TextBase::showEditor()::{lambda()#1}&) ()
#11 0x0000555555f6d156 in std::enable_if<is_invocable_r_v<void, TextBase::showEditor()::{lambda()#1}&>, void>::type std::__invoke_r<void, TextBase::showEditor()::{lambda()#1}&>(TextBase::showEditor()::{lambda()#1}&) ()
#12 0x0000555555f66c82 in std::_Function_handler<void (), TextBase::showEditor()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#13 0x00005555557f60f8 in std::function<void ()>::operator()() const ()
#14 0x00005555559cd5a8 in void juce::NullCheckedInvocation::invoke<std::function<void ()>&>(std::function<void ()>&) ()
#15 0x000055555590ba9d in juce::TextEditor::handleCommandMessage(int) ()
#16 0x000055555588b7ad in juce::Component::postCommandMessage(int)::{lambda()#1}::operator()() const ()
#17 0x000055555594d3f4 in void std::__invoke_impl<void, juce::Component::postCommandMessage(int)::{lambda()#1}&>(std::__invoke_other, juce::Component::postCommandMessage(int)::{lambda()#1}&) ()
#18 0x0000555555948728 in std::enable_if<is_invocable_r_v<void, juce::Component::postCommandMessage(int)::{lambda()#1}&>, void>::type std::__invoke_r<void, juce::Component::postCommandMessage(int)::{lambda()#1}&>(juce::Component::postCommandMessage(int)::{lambda()#1}&) ()
#19 0x0000555555944335 in std::_Function_handler<void (), juce::Component::postCommandMessage(int)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#20 0x00005555557f60f8 in std::function<void ()>::operator()() const ()
#21 0x0000555555b83014 in juce::MessageManager::callAsync(std::function<void ()>)::AsyncCallInvoker::messageCallback() ()
#22 0x0000555555b8d673 in juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}::operator()(int) const ()
#23 0x0000555555b9d3c6 in void std::__invoke_impl<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(std::__invoke_other, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) ()
#24 0x0000555555b99cb5 in std::enable_if<is_invocable_r_v<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>, void>::type std::__invoke_r<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) ()
#25 0x0000555555b95a28 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#26 0x0000555555a0e6f8 in std::function<void (int)>::operator()(int) const ()
--Type <RET> for more, q to quit, c to continue without paging--
#27 0x0000555555b887bd in juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}::operator()() const ()
#28 0x0000555555b89792 in void std::__invoke_impl<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(std::__invoke_other, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
#29 0x0000555555b891ea in std::enable_if<is_invocable_r_v<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>, void>::type std::__invoke_r<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&>(juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}&) ()
#30 0x0000555555b88ea4 in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#31 0x00005555557f60f8 in std::function<void ()>::operator()() const ()
#32 0x0000555555b8df26 in juce::InternalRunLoop::dispatchPendingEvents() ()
#33 0x0000555555b88770 in juce::dispatchNextMessageOnSystemQueue(bool) ()
#34 0x0000555555b82d19 in juce::MessageManager::runDispatchLoop() ()
#35 0x0000555555b8231f in juce::JUCEApplicationBase::main() ()
#36 0x0000555555b8224e in juce::JUCEApplicationBase::main(int, char const**) ()
#37 0x0000555555769f65 in main ()
```
and from release version
```
Thread 1 "release" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a9f988 in vtable for __cxxabiv1::__si_class_type_info () from /usr/lib/libstdc++.so.6
(gdb) bt
#0  0x00007ffff7a9f988 in vtable for __cxxabiv1::__si_class_type_info () from /usr/lib/libstdc++.so.6
#1  0x0000555555e2547d in libpd_get_object_bounds ()
#2  0x0000555555cfd94e in TextObjectHelper::recalculateTextObjectBounds(void*, void*, juce::String const&, int, int&, bool, int) ()
#3  0x0000555555cfe363 in TextBase::getPdBounds() ()
#4  0x0000555555ca8b10 in Object::updateBounds() ()
#5  0x0000555555d0d184 in KeyboardObject::KeyboardObject(void*, Object*) ()
#6  0x0000555555cbbd80 in ObjectBase::createGui(void*, Object*) ()
#7  0x0000555555caa884 in Object::setType(juce::String const&, void*) ()
#8  0x0000555555d107e1 in std::_Function_handler<void (), TextBase::showEditor()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#9  0x0000555555886761 in juce::TextEditor::handleCommandMessage(int) ()
#10 0x0000555555a028c7 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#11 0x00005555559f44ce in std::_Function_handler<void (), juce::LinuxEventLoop::registerFdCallback(int, std::function<void (int)>, short)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#12 0x00005555559ff571 in juce::MessageManager::runDispatchLoop() ()
#13 0x000055555568e389 in juce::JUCEApplicationBase::main() ()
#14 0x00007ffff754720c in __libc_start_call_main (main=main@entry=0x5555556842c0 <main>, argc=argc@entry=1, 
    argv=argv@entry=0x7fffffffe848) at ../sysdeps/nptl/libc_start_call_main.h:58
#15 0x00007ffff75472bc in __libc_start_main_impl (main=0x5555556842c0 <main>, argc=1, argv=0x7fffffffe848, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe838)
    at ../csu/libc-start.c:381
#16 0x00005555556d5ab1 in _start () at ../sysdeps/x86_64/start.S:115
```

**Comment by tomara-x** [comment]
and holy nuts! what is going on in the keyboard help file?

**Comment by tomara-x** [comment]
so it is in fact created, just.. idk

https://user-images.githubusercontent.com/86204514/224678055-697b03f6-b168-4cd8-aa8a-8667c6f54d1c.mp4

and the saved file is:
```
#N canvas 827 239 527 327 12;
#X obj 150 350 keyboard 17 80 4 2 0 0 empty empty;
#X obj 150 438 keyboard 17 80 4 2 0 0 empty empty;
```

**Comment by tomara-x** [comment]
it is actually created (notice how there are two when loaded in pd)

https://user-images.githubusercontent.com/86204514/224679802-411132d3-c1bd-41d2-8afe-086626f9ac72.mp4

**Comment by timothyschoen** [comment]
Fixed!

**Comment by tomara-x** [comment]
nice work you two!
it gets an extra black area to the right when it gets duplicated or moved with keyboard arrows
