### ISSUE TITLE
Crash when closing the Plugdata window

### ISSUE THREAD

**Issue by Yzrsah** [plugdata-team/plugdata#719]
Host is crashing when closing the Plugdata window.
Tested In Bitwig and Reaper on Windows 10.

Steps to reproduce:
1) Load Plugdata VST3 or CLAP
2) Make a New Patch
3) Close Plugdata window
4) Host Crashes

**Comment by timothyschoen** [comment]
Hi, are you using v0.7.0 or the nightly v0.7.1?

**Comment by timothyschoen** [comment]
oops

**Comment by haenkel** [comment]
I can confirm this for reaper/linux too
backtrace is with a vst3 compiled at 3cd921a56ae5f822b81f560276c888313846accc

```gdb
Thread 1 "reaper" received signal SIGSEGV, Segmentation fault.
0x00007fffb30d163a in juce::ArrayBase<juce::TabbedButtonBar::TabInfo*, juce::DummyCriticalSection>::size (this=0x130) at plugdata/Libraries/JUCE/modules/juce_core/containers/juce_ArrayBase.h:201
201	        return numUsed;
(gdb) bt
#0  0x00007fffb30d163a in juce::ArrayBase<juce::TabbedButtonBar::TabInfo*, juce::DummyCriticalSection>::size() const (this=0x130)
    at plugdata/Libraries/JUCE/modules/juce_core/containers/juce_ArrayBase.h:201
#1  0x00007fffb3095baa in juce::OwnedArray<juce::TabbedButtonBar::TabInfo, juce::DummyCriticalSection>::size() const (this=0x130)
    at plugdata/Libraries/JUCE/modules/juce_core/containers/juce_OwnedArray.h:131
#2  0x00007fffb2f76988 in juce::TabbedButtonBar::getNumTabs() const (this=0x0)
    at plugdata/Libraries/JUCE/modules/juce_gui_basics/layout/juce_TabbedButtonBar.cpp:315
#3  0x00007fffb2f7858c in juce::TabbedComponent::getNumTabs() const
    (this=0x24fa240)
    at plugdata/Libraries/JUCE/modules/juce_gui_basics/layout/juce_TabbedComponent.cpp:183
#4  0x00007fffb358a4d9 in TabComponent::getIndexOfCanvas(Canvas*)
    (this=0x24fa240, cnv=0x4a4d8d0)
    at plugdata/Source/Tabbar.h:196
#5  0x00007fffb357844f in Canvas::getTabbar() (this=0x4a4d8d0)
    at plugdata/Source/Canvas.cpp:210
#6  0x00007fffb376a86d in PluginEditor::getZoomScaleValueForCanvas(Canvas*)
    (this=0x24f9970, cnv=0x4a4d8d0)
    at plugdata/Source/PluginEditor.cpp:1448
```

**Comment by Yzrsah** [comment]
> Hi, are you using v0.7.0 or the nightly v0.7.1?

A nightly from yesterday. I usually download a new copy every day after it looks like work has finished.
I think it was https://github.com/plugdata-team/plugdata/commit/a8c9830274faad6571246ddd6253cb86d04d2a73

**Comment by timothyschoen** [comment]
@Nejrup fixed it!
