### ISSUE TITLE
issues with having multiple tabs when closing/reopening plugin mode window

### ISSUE THREAD

**Issue by tomara-x** [plugdata-team/plugdata#817]
i notice here that:
- when reopening the window it's open to a different tab than the one it had when closing it
- when leaving plugin mode and back to the editor, the tab that was visible is fine, but the other tab looks empty and can't be closed

https://user-images.githubusercontent.com/86204514/231939252-7ccfdaa9-a27f-49c2-be0c-cd28d9388b2d.mp4

https://user-images.githubusercontent.com/86204514/231939271-04f6969a-5fac-4024-9934-fbeef8af975a.mp4

**Comment by tomara-x** [comment]
tried taking one of those empty looking patches from here and dragging it into a new split and:
```
Thread 1 "reaper" received signal SIGSEGV, Segmentation fault.
0x00007fff7f2794d3 in SplitView::splitCanvasView (this=0x40468e8, cnv=0x0, splitViewFocus=true)
    at /home/void/plugdata/Source/SplitView.cpp:315
315	    auto* editor = cnv->editor;
(gdb) bt
#0  0x00007fff7f2794d3 in SplitView::splitCanvasView (this=0x40468e8, cnv=0x0, splitViewFocus=true)
    at /home/void/plugdata/Source/SplitView.cpp:315
#1  0x00007fff7f27994d in SplitView::mouseUp (this=0x40468e8, e=...)
    at /home/void/plugdata/Source/SplitView.cpp:391
#2  0x00007fff7ee6ae08 in juce::Component::MouseListenerList::sendMouseEvent<void (juce::MouseListener::*)(juce::MouseEvent const&)>(juce::HierarchyChecker&, void (juce::MouseListener::*&&)(juce::MouseEvent const&))::{lambda(auto:1&, auto:2)#1}::operator()<juce::Component, juce::Component::MouseListenerList::sendMouseEvent<void (juce::MouseListener::*)(juce::MouseEvent const&)>(juce::HierarchyChecker&, void (juce::MouseListener::*&&)(juce::MouseEvent const&))::{lambda(auto:1&)#3}>(void (juce::MouseListener::*&)(juce::MouseEvent const&), juce::Component::MouseListenerList::sendMouseEvent<void (juce::MouseListener::*)(juce::MouseEvent const&)>(juce::HierarchyChecker&, void (juce::MouseListener::*&&)(juce::MouseEvent const&))::{lambda(auto:1&)#3}) const (
    __closure=0x7fffffffd810, parentComp=..., findNumListeners=...)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:134
#3  0x00007fff7ee6afc9 in juce::Component::MouseListenerList::sendMouseEvent<void (juce::MouseListener::*)(juce::MouseEvent const&)> (checker=..., 
    eventMethod=@0x7fffffffd900: &virtual juce::MouseListener::mouseUp(juce::MouseEvent const&))
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:150
#4  0x00007fff7ed3771a in juce::Component::internalMouseUp (this=0x5a3e2b0, source=..., 
    relativePointerState=..., time=..., oldModifiers=...)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/components/juce_Component.cpp:2563
#5  0x00007fff7ee15742 in juce::MouseInputSourceInternal::sendMouseUp (this=0x4c53e70, comp=..., 
    pointerState=..., time=..., oldMods=...)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:140
#6  0x00007fff7ee15a63 in juce::MouseInputSourceInternal::setButtons (this=0x4c53e70, pointerState=..., 
    time=..., newButtonState=...)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:185
#7  0x00007fff7ee16230 in juce::MouseInputSourceInternal::handleEvent (this=0x4c53e70, newPeer=..., 
    positionWithinPeer=..., time=..., newMods=..., newPressure=0, newOrientation=0, pen=...)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:313
#8  0x00007fff7ed3b020 in juce::MouseInputSource::handleEvent (this=0x7fffffffdd70, peer=..., pos=..., 
    time=1681446194195, mods=..., pressure=0, orientation=0, penDetails=...)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:610
#9  0x00007fff7edc8843 in juce::ComponentPeer::handleMouseEvent (this=0x4b1e340, 
    type=juce::MouseInputSource::mouse, pos=..., newMods=..., newPressure=0, newOrientation=0, 
    time=1681446194195, pen=..., touchIndex=0)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/windows/juce_ComponentPeer.cpp:90
#10 0x00007fff7ede9bd7 in juce::XWindowSystem::handleButtonReleaseEvent (this=0x7fffa40207c0, 
    peer=0x4b1e340, buttonRelEvent=...)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3591
#11 0x00007fff7ede8d6a in juce::XWindowSystem::handleWindowMessage (this=0x7fffa40207c0, peer=0x4b1e340, 
    event=...)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3323--Type <RET> for more, q to quit, c to continue without paging--

#12 0x00007fff7edeaf91 in juce::XWindowSystem::windowMessageReceive (event=...)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3909
#13 0x00007fff7ede8514 in operator() (__closure=0x7fffa400c740)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_gui_basics/native/x11/juce_linux_XWindowSystem.cpp:3245
#14 0x00007fff7ee024e6 in std::__invoke_impl<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/12.2/bits/invoke.h:61
#15 0x00007fff7edfd57e in std::__invoke_r<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int>(struct {...} &) (__fn=...) at /usr/include/c++/12.2/bits/invoke.h:111
#16 0x00007fff7edf7f0b in std::_Function_handler<void(int), juce::XWindowSystem::initialiseXDisplay()::<lambda(int)> >::_M_invoke(const std::_Any_data &, int &&) (__functor=..., __args#0=@0x7fffffffe064: 18)
    at /usr/include/c++/12.2/bits/std_function.h:290
#17 0x00007fff7eee91ea in std::function<void (int)>::operator()(int) const (this=0x7fffa400c740, __args#0=18)
    at /usr/include/c++/12.2/bits/std_function.h:591
#18 0x00007fff7f0594bd in operator() (__closure=0x7fffa400c740)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:357
#19 0x00007fff7f05a492 in std::__invoke_impl<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()>&>(std::__invoke_other, struct {...} &) (__f=...)
    at /usr/include/c++/12.2/bits/invoke.h:61
#20 0x00007fff7f059eea in std::__invoke_r<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()>&>(struct {...} &) (__fn=...) at /usr/include/c++/12.2/bits/invoke.h:111
#21 0x00007fff7f059ba4 in std::_Function_handler<void(), juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/12.2/bits/std_function.h:290
#22 0x00007fff7ece189a in std::function<void ()>::operator()() const (this=0x7fffa4013bb0)
    at /usr/include/c++/12.2/bits/std_function.h:591
#23 0x00007fff7f05f16b in juce::InternalRunLoop::dispatchEvent (this=0x4c1b050, fd=18)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:196
#24 0x00007fff7f0596bc in juce::LinuxEventLoopInternal::invokeEventLoopCallbackForFd (fd=18)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_events/native/juce_linux_Messaging.cpp:382
#25 0x00007fff7ec55805 in juce::EventHandler::onFDIsSet (this=0x402a220, fd=18)
    at /home/void/plugdata/Libraries/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:186
#26 0x00000000009a13cc in ?? ()
#27 0x00007ffff74314d8 in ?? () from /home/void/Downloads/reaper_linux_x86_64/REAPER/libSwell.so
#28 0x000000000040c6e6 in ?? ()
#29 0x00007ffff784120c in __libc_start_call_main (main=main@entry=0x40bd10, argc=argc@entry=1, 
    argv=argv@entry=0x7fffffffe838) at ../sysdeps/nptl/libc_start_call_main.h:58
#30 0x00007ffff78412bc in __libc_start_main_impl (main=0x40bd10, argc=1, argv=0x7fffffffe838, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe828)
    at ../csu/libc-start.c:381
#31 0x0000000000419dca in _start ()
```

**Comment by timothyschoen** [comment]
Should be fixed, but I had to rewrite the whole mechanism for restoring plugin mode, so let me know if you have any more issues.

**Comment by tomara-x** [comment]
thank you! will do <3
